#!/usr/bin/bash

echo -n "tenant id: "
read tenant
#aws s3api --endpoint-url https://192.168.4.230:10443 --no-verify-ssl create-bucket --bucket testbucket --profile grid
aws s3api --endpoint-url https://192.168.4.230:10443 --no-verify-ssl list-buckets  --profile grid
#aws s3api --endpoint-url https://192.168.4.230:10443 --no-verify-ssl delete-bucket --bucket testbucket --profile grid


