#this playbook uses the sgrid_auth_B.json file to get the account id
#of the tenant. So you will need to edit this file for the right id.
---
- name: Create StorageGRID Bucket
  hosts: localhost
  gather_facts: no
  collections:
    - netapp.storagegrid
  vars_prompt:
    - name: bucket_name
      prompt: "enter bucket name"
      default: "default"
      private: no
    - name: tenant_id
      prompt: "enter tenant id"
      default: "default"
      private: no
    - name: tenant_username
      prompt: "enter tenant user"
      default: "default"
      private: no
    - name: tenant_password
      prompt: "enter tenant password" 
      default: "default"
      private: no

  vars_files:
    global_vars.yml

  tasks:
    - name: Get Tenant Authorization Token
      uri:
        url: "{{ grid_endpoint }}/api/v3/authorize"
        method: POST
        body: '{"accountId": "{{ tenant_id }}", 
                "username": "{{ tenant_username }}", 
                "password": "{{ tenant_password }}"}'
        body_format: json
        validate_certs: false
        status_code: [200]
      register: auth
#
#the authtoken can be processes as auth.json.data (variable)
#
    - name: Display Tenant Auth Token
      ansible.builtin.debug:
        msg: "Tenant Auth Token: {{ auth.json.data }}"

    - name: Create S3 Bucket
      netapp.storagegrid.na_sg_org_container:
        api_url: "https://192.168.4.230:443"
        #auth_token: "{{ auth.json.data }}"
        auth_token: 160c48d7-cc5a-457c-9d52-8e784aa9a010 
        validate_certs: false
        state: present
        name: "{{ bucket_name }}"
        region: us-east-1
