#this playbook uses hardcoded tenant data for authorization
#of the tenant. 
---
- name: Create StorageGRID Bucket
  hosts: localhost
  gather_facts: no
  collections:
    - netapp.storagegrid
  vars_prompt:
    - name: bucket_name
      prompt: "enter bucket name"
      default: "default"
      private: no
    - name: account_id
      prompt: "enter account_id"
      default: "default"
      private: no
  roles:
    - tenant_auth 
  tasks:
    - name: Create S3 Bucket
      netapp.storagegrid.na_sg_org_container:
        api_url: "https://192.168.4.230:443"
        auth_token: "{{ auth.json.data }}"
        validate_certs: false
        state: present
        name: "{{ bucket_name }}"
        region: us-east-1
