---
- name: List StorageGRID tenants
  hosts: localhost
  gather_facts: false
  vars:
  vars_files:
    global_vars.yml
  roles:
    - grid_auth
  tasks:
    - name: Get list of tenants from StorageGRID
      uri:
        url: "{{ grid_endpoint }}/api/v3/grid/accounts"
        method: GET
        headers:
          Authorization: "Bearer {{ bearer_token }}"
          Accept: "application/json"
        validate_certs: false
      register: tenants

    - name: Display tenants JSON
      debug:
        var: tenants.json

