---
- name: List StorageGRID tenants
  hosts: localhost
  gather_facts: false
  vars:
  vars_files:
    global_vars.yml

  tasks:
    - name:
      ansible.builtin.import_role:
        name: grid_auth

    - name: Get list of tenants from StorageGRID
      uri:
        url: "https://{{ admin_node }}/api/v3/grid/accounts"
        method: GET
        headers:
          Authorization: "Bearer {{ bearer_token }}"
          Accept: "application/json"
        validate_certs: false
      register: tenant_response

    - name: Display tenants JSON
      debug:
        var: tenant_response.json
